# Generated by Django 5.2 on 2025-04-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('batting_style', models.CharField(choices=[('Right', 'Right-handed'), ('Left', 'Left-handed')], max_length=10)),
                ('bowling_style', models.CharField(choices=[('Fast', 'Fast bowler'), ('Medium', 'Medium pace'), ('Spin', 'Spin bowler'), ('NA', 'Not a bowler')], max_length=10)),
                ('role', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('jersey_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(blank=True, choices=[('Bat', 'Bat'), ('Field', 'Field')], max_length=10, null=True)),
                ('result', models.CharField(choices=[('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('No Result', 'No Result'), ('TBD', 'To Be Determined')], default='TBD', max_length=20)),
                ('umpires', models.CharField(max_length=200)),
                ('match_number', models.PositiveIntegerField(unique=True)),
                ('man_of_the_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.player')),
            ],
        ),
        migrations.CreateModel(
            name='BowlingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('maidens', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('no_balls', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_performances', to='tournament.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_performances', to='tournament.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('not_out', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_performances', to='tournament.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_performances', to='tournament.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('home_ground', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('founded', models.PositiveIntegerField()),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='tournament.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_wins', to='tournament.team'),
        ),
    ]
