# Generated by Django 5.2 on 2025-04-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='balls_remaining',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='match',
            name='current_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batsman_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bowler_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='innings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='battingperformance',
            unique_together={('player', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='bowlingperformance',
            unique_together={('player', 'match')},
        ),
    ]
