# Generated by Django 5.2 on 2025-04-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_team_manager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battingperformance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bowlingperformance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='best_bowling_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_bowling_wickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='centuries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_balls_faced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_catches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_fours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_overs_bowled',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='total_run_outs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_runs_conceded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_sixes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_stumpings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battingperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.match'),
        ),
        migrations.AlterField(
            model_name='bowlingperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.match'),
        ),
        migrations.RemoveField(
            model_name='bowlingperformance',
            name='no_balls',
        ),
        migrations.RemoveField(
            model_name='bowlingperformance',
            name='wides',
        ),
    ]
