# Generated by Django 5.2 on 2025-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
