# Generated by Django 5.2 on 2025-04-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_match_away_byes_match_away_extras_match_away_legbyes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_ball',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='current_non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_non_striker_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_over',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='next_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_batsman_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_bowler_matches', to='tournament.player'),
        ),
    ]
