# Generated by Django 5.2 on 2025-04-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_match_batting_team_match_current_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowler_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striker_matches', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striker_matches', to='tournament.player'),
        ),
    ]
