# Generated by Django 5.2 on 2025-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_match_bowler_match_non_striker_match_striker'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingperformance',
            name='innings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bowlingperformance',
            name='innings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
