# Generated by Django 5.2 on 2025-04-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_match_bowler_balls_match_bowler_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowling_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_matches', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='batting_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_matches', to='tournament.team'),
        ),
    ]
