# Generated by Django 5.2 on 2025-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_remove_match_away_byes_remove_match_away_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='ball_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ball',
            name='over',
            field=models.IntegerField(default=1),
        ),
    ]
