# Generated by Django 5.2 on 2025-04-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_ball_ball_number_ball_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowler_no_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_wides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_current_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_innings', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='first_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_current_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_current_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_innings', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='wicket_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='batting_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_matches', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowler_matches', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowler_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowler_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowling_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_matches', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striker_matches', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striker_matches', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(choices=[('bat', 'Bat'), ('field', 'Field')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_wins', to='tournament.team'),
        ),
    ]
