# Generated by Django 5.2 on 2025-04-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_match_bowler_no_balls_match_bowler_wides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingperformance',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_dismissals', to='tournament.player'),
        ),
    ]
