# Generated by Django 5.2 on 2025-04-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_battingperformance_bowler'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder_balls', to='tournament.player'),
        ),
    ]
