# Generated by Django 5.2 on 2025-04-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_ball_fielder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='fielder',
        ),
    ]
