# Generated by Django 5.2 on 2025-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_remove_ball_fielder'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
