# Generated by Django 5.2 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_team_total_matches_alter_team_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlingperformance',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlingperformance',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlingperformance',
            name='overs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlingperformance',
            name='runs_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlingperformance',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
