# Generated by Django 5.2 on 2025-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_bowlingperformance_economy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bowler_balls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_powerplay',
        ),
        migrations.RemoveField(
            model_name='match',
            name='powerplay_overs',
        ),
        migrations.RemoveField(
            model_name='match',
            name='powerplay_runs',
        ),
        migrations.RemoveField(
            model_name='match',
            name='powerplay_wickets',
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_overs',
            field=models.IntegerField(default=0),
        ),
    ]
