# Generated by Django 5.2 on 2025-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_remove_match_bowler_balls_remove_match_is_powerplay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bowler_overs',
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_balls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='is_powerplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='powerplay_overs',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='match',
            name='powerplay_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='powerplay_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
