# Generated by Django 5.2 on 2025-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_remove_match_bowler_overs_match_bowler_balls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='batter1',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='batter2',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='match',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='wicket',
        ),
        migrations.DeleteModel(
            name='DRS',
        ),
        migrations.DeleteModel(
            name='Partnership',
        ),
    ]
